export { createDatabase, schema } from './client.js'
export type { Database } from './client.js'
export { migrationsFolderUrl } from './migrations-path.js'
export * from './schema/auth.js'
export * from './schema/interactions.js'
export * from './schema/media.js'
export * from './schema/notifications.js'
export * from './schema/posts.js'
export * from './schema/social-graph.js'
export * from './schema/users.js'
